### ISSUE TITLE
[feature-request] RabbitMQ support

### ISSUE THREAD

**Issue by itrofimow** [yandex/yandex-taxi-testsuite#11]
I'm working on amqp support in userver (https://github.com/userver-framework/userver/issues/44), and it would be great if you guys could support RabbitMQ on your side. 

P.S. I could give it a shot myself if you don't have time for that, so please let me know

**Comment by vitek** [comment]
We don't use RabbitMQ at the moment. So feel free to implement it yourself.

**Comment by itrofimow** [comment]
Closed by https://github.com/yandex/yandex-taxi-testsuite/pull/12
