### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by Kaveshnikov** [yandex/yandex-taxi-testsuite#2]
Hi!
I was looking for an installation instruction in this repository and documentation but didn't find any. I also did not find a package on pypi. Do you advise to install this framework from git?

**Comment by vitek** [comment]
Currently the only supported installation methods are using it as git submodule or installing inside your local virtualenv. You are right that it should be available on pypi will be fixed in the following version.

**Comment by Kaveshnikov** [comment]
Oh, ok. When do you plan to release the next version?

**Comment by vitek** [comment]
fixed, see https://github.com/yandex/yandex-taxi-testsuite#installation
